export class User {
    constructor( 
    public r0c0: number, 
    public r0c1: number, 
    public r0c2: number, 
    public r0c3: number, 
    public r0c4: number, 
    public r0c5: number, 
    public r0c6: number, 
    public r0c7: number, 
    public r0c8: number, 

    public r1c0: number, 
    public r1c1: number, 
    public r1c2: number, 
    public r1c3: number, 
    public r1c4: number, 
    public r1c5: number, 
    public r1c6: number, 
    public r1c7: number, 
    public r1c8: number, 

    public r2c0: number, 
    public r2c1: number, 
    public r2c2: number, 
    public r2c3: number, 
    public r2c4: number, 
    public r2c5: number, 
    public r2c6: number, 
    public r2c7: number, 
    public r2c8: number, 

    public r3c0: number, 
    public r3c1: number, 
    public r3c2: number, 
    public r3c3: number, 
    public r3c4: number, 
    public r3c5: number, 
    public r3c6: number, 
    public r3c7: number, 
    public r3c8: number, 

    public r4c0: number, 
    public r4c1: number, 
    public r4c2: number, 
    public r4c3: number, 
    public r4c4: number, 
    public r4c5: number, 
    public r4c6: number, 
    public r4c7: number, 
    public r4c8: number, 

    public r5c0: number, 
    public r5c1: number, 
    public r5c2: number, 
    public r5c3: number, 
    public r5c4: number, 
    public r5c5: number, 
    public r5c6: number, 
    public r5c7: number, 
    public r5c8: number, 

    public r6c0: number, 
    public r6c1: number, 
    public r6c2: number, 
    public r6c3: number, 
    public r6c4: number, 
    public r6c5: number, 
    public r6c6: number, 
    public r6c7: number, 
    public r6c8: number,  

    public r7c0: number, 
    public r7c1: number, 
    public r7c2: number, 
    public r7c3: number, 
    public r7c4: number, 
    public r7c5: number, 
    public r7c6: number, 
    public r7c7: number, 
    public r7c8: number, 

    public r8c0: number, 
    public r8c1: number, 
    public r8c2: number, 
    public r8c3: number, 
    public r8c4: number, 
    public r8c5: number, 
    public r8c6: number, 
    public r8c7: number, 
    public r8c8: number, 
    ){}
}

